cc_library(
    name = "ivf",
    hdrs = ["IVF.h",
            "posting_list.h",
            "clustering.h"],
    deps = [
        "@parlaylib//:parlay:sequence",
        "@parlaylib//:parlay:internal",
        "@parlaylib//:parlay:parallel",
        "@parlaylib//:parlay:io",
    ],
    visibility = ["//visibility:public"],
)
